on: [push, pull_request]

name: release

jobs:
  build:
    name: Create new release with WASM artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-wasi
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=wasm32-wasi --release
